version: '3.8'
services:

  # Configuracion del servicio de backend 
  backend:  
    build: 
      context: .
      dockerfile: php.dockerfile
    container_name: backend_svc
    ports:
      - 8080:80 #vincula el puerto 80 del contenedor con el puerto local 8080
    volumes:
      - ./www/:/var/www/html #Coloca el directorio local www en esa direccion del contenedor
    depends_on:
      - database #Depende del servicio database
    networks:
      app_network:
        aliases:
          - backend_host #Alias para el servicio de red 

  #Configuracion del servicio de base de datos
  database:
    build: 
      context: .
      dockerfile: mariadb.dockerfile
    container_name: mariadb_svc
    ports:
      - 3306:3306 #vincula el puerto 3306 del contenedor con el puerto local 3306
    environment:
      MYSQL_DATABASE: "usuarios_db" #Define el nombre de la base de datos
      MYSQL_ROOT_PASSWORD: "Custom.2023" #Define la contraseña del usuario root
    volumes:
      - ./schemas/:/var/lib/mysql #Coloca el directorio local schemas en esa direccion del contenedor
        #Coloca el archivo schema.sql en docker-entrypoint-initdb.d/schema.sql , que permite iniciar una tabla con su estructura dentro de la bd
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql 
    networks:
      app_network:
        aliases:
          - mariadb_host #Alias para el servicio en la red

#Definicion de volumenes para el servicio de backend y de database
volumes:
  www: {}
  schemas: {}

networks:
  app_network:
    name: app_net #Nombre dado a la red
    driver: bridge #El tipo de red usada
    ipam:
      driver: default #Configuracion por default del administador de direcciones IP